name: docs

on:
  push:
    branches: [ master ]
    paths: [ 'docs/devote-api.yml' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Github Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create docs
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle docs/devote-api.yml --output docs/index.html'

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs